# 00: (Very) Brief introduction to Scientific Computing with Python

In this notebook we explore together some Python features, especially we will focus on Numpy, a package for scientific computing that closely resembles Matlab.

You are invited to check https://numpy.org/doc/stable/user/numpy-for-matlab-users.html for a complete Numpy for Matlab users guide.

Let's begin. Say we come from Matlab and we kid ourselves into thinking that we can just do this:

In [1]:
a = [1,2,3]

and have an array with the expected Matlab's vectors behavior

In [2]:
a

[1, 2, 3]

Well, that doesn't look so bad, right? Let's try now

In [3]:
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

what the...?
Well, a is a "tuple", that is an heterogeneous collection of 3 objects, in our case numbers. As a matter of fact, one can also write

In [4]:
a = [ 1,'a',[1,2]]
a

[1, 'a', [1, 2]]

Pretty confusing, right? What we actually wanted was a Matlab-like behaviour, that is offered by the Numpy package:

In [5]:
import numpy as np  # that we have to import

a = np.array([1,2,3])
3*a

array([3, 6, 9])

Much better, right? Provided we use Numpy arrays to do our things, Python works pretty much like Matlab, with some caveats:

0. The first element of something is indexed as 0 (and not 1)

In [6]:
a = np.array([1,2,3])
print(a[0])

1


1. Unless expressly specified, in Python everything works as it it was "pointed at"

In [7]:
a = np.array([1,2,3])
print(a[0]) # as expected

1


In [8]:
b = a
b[0] = 100
print(a[0]) # very unexpected

100


In [9]:
c = a.copy()
c[0] = -1
print(a[0]) # back to expected behavior

100


2. Numpy is less pedantic with array shapes. This is unsettling at first but you'll learn to love it

In [21]:
A = np.array([[1,2,3],[4,5,6]])
print( A.shape ) # as expected

(2, 3)


In [22]:
a = A[0,:] # we would expect its size to be (1,3)
print( a.shape ) # unexpected

(3,)


In [23]:
a = A[:,0] # we would expect its size to be (2,1)
print( a.shape ) # unexpected

(2,)


In [24]:
print( A[:,0][:,None].shape ) # back to expected behavior

(2, 1)


In [25]:
print( A[:,0][None,:].shape ) # back to expected behavior

(1, 2)


In [26]:
print( A[0,:][:,None].shape ) # back to expected behavior

(3, 1)


In [27]:
print( A[0,:][None,:].shape ) # back to expected behavior

(1, 3)


In [28]:
print( np.array([1,2,3]).shape ) # maybe you didn't expect it yet

(3,)


In [29]:
print( a[None,:,None,None].shape ) # lol

(1, 2, 1, 1)


4. Now look at these indexing

In [ ]:
a = np.array([1,2,3,4,5,6])

ways to print all a

In [39]:
print( a )
print( a[:])
print( a[0:])

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


ways to print the first 3 entries of a

In [40]:
print( a[0:3] )      # unexpected, right? You would have said a[0:2], like, 0,1,2!
print( a[range(3)] ) # unexpected, right?
print( a[:3] )       # unexpected, right?

[1 2 3]
[1 2 3]
[1 2 3]


how to print from second to last entry

In [41]:
print( a[1:] )

[2 3 4 5 6]


how to print last element of a

In [42]:
print( a[-1] )

6


how to print second to last element of a

In [43]:
print( a[-2] )

5


how to print from third (3, so index 2) to second to last element (5, that is -2)

In [44]:
print( a[2:-1] ) # when n:m remember that m is not included!

[3 4 5]


Now, a words about performances. Matlab probably spoiled you with JIT (Just In Time compiling) and you did not even realise it. In fact Matlab at the first run of a code performs a light compiling and execution, driving down your loops costs and speeding up your codes (greatly).

Python won't do this. Or at least not on its own, you need to import other packages, as Numba.

This forces you to write code as a professional: avoid looping, avoid boolean flow controls, write "vectorial" code.

Let's see an example. To time stuff we need to import time:

In [12]:
import time

In [45]:
t = time.time()
n = 10000 # attention: if I write 1e4 it'll assume n is a float and break range, which only accepts int
m = 1000  # attention: if I write 1e3 it'll assume m is a float and break range, which only accepts int
for i in range(n):
    for j in range(m):
        c = 1.
print('Elapsed time is %1.2f seconds.' % ( time.time() - t ) ) # 720ms

Elapsed time is 0.62 seconds.


On this same machine, Matlab executes this in 53ms on the first launch, then 8ms on avg. See also, https://www.youtube.com/watch?v=d7KHAVaX_Rs

As for the rest, you do pretty much what you would do in Matlab, at the beginning constantly making sure that everything checks out.

#### Example 01:

In [14]:
A = np.array( range(3*3) ).reshape(3,3)
B = np.array( range(3*3) ).reshape(3,3)

print( A )
print(' ')

print( B )
print(' ')

print(A*B) # unexpected, right?
print(' ')

print(A@B) # that's what you wanted

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
 
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


#### Example 02:

Sometimes it is not exactly immediate.

In [15]:
A = np.array([[1,2],[2,1]])
B = np.eye(2)

print('print(np.linalg.norm(A-B)):')
print(np.linalg.norm(A-B))

print(np.linalg.norm(A-B)):
2.8284271247461903


#### Example 03:

Sometimes, some of the Matlab functions you are used to can be found inside a package called Scipy

In [47]:
from scipy import linalg
A = np.random.randn(3,3)
A @ linalg.inv(A)

array([[ 1.00000000e+00,  6.31991419e-17, -7.09560472e-17],
       [ 3.13213669e-17,  1.00000000e+00, -9.57538576e-17],
       [-3.94960429e-16,  4.75729116e-17,  1.00000000e+00]])

Now pay attention:

In [17]:
A = np.random.randn( 2000,10000)
B = np.random.randn(10000, 2000)

t = time.time()
C = A@B
print('Elapsed time is %1.2f seconds.' % ( time.time() - t ) ) # 1.21s vs MATLAB's 1.22s

Elapsed time is 1.49 seconds.


Matlab instead took 1.22 seconds to perform the same task. Why that? Because both Matlab and Numpy run BLAS under the hood.

What are BLAS?

Short answer: your best friends. 

Long answer: The BLAS (Basic Linear Algebra Subprograms) are routines that provide standard building blocks for performing basic vector and matrix operations. The Level 1 BLAS perform scalar, vector and vector-vector operations, the Level 2 BLAS perform matrix-vector operations, and the Level 3 BLAS perform matrix-matrix operations. Because the BLAS are efficient, portable, and widely available, they are commonly used in the development of high quality linear algebra software, LAPACK for example.

See also https://www.netlib.org/blas/

Matlab, typically runs proprietary BLAS https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2023-0/blas-and-sparse-blas-routines.html (proprietary = someone pays for it) while Octave, Numpy and open source software in general use open source BLAS instead.

You most likely won't even notice the difference in performance. Also, Numpy provides a by far more clever way to exploit BLAS (and batched BLAS).
For example, an array an array with shape (n,m,p) and a (n,p,l) shaped array can be multiplied together (try to do that in Matlab)

In [18]:
n = 10
m = 3
p = 2 
l = 4
A = np.array(range(n*m*p)).reshape(n,m,p)
B = np.array(range(n*p*l)).reshape(n,p,l)
C = A @ B

print('print( A.shape ):')
print( A.shape )

print('\nprint( B.shape ):')
print( B.shape )

print('\nprint( C.shape ):')
print( C.shape )

print( A.shape ):
(10, 3, 2)

print( B.shape ):
(10, 2, 4)

print( C.shape ):
(10, 3, 4)


Numpy in fact sees the array A as a stack of n matrices (m,p) multiplied each for the corresponding mate from the stack B of n matrices (p,l).

This can be generalised:

In [19]:
D = np.random.randn(3,4,5,6) # a (3,4) stack of (5,6) arrays
E = np.random.randn(3,4,6,3) # a (3,4) stack of (6,3) arrays
F = D @ E
print('print( F.shape ):')
print( F.shape ) 

print( F.shape ):
(3, 4, 5, 3)


Also, Numpy is so clever that supports strided transposition.

What is that?? Well, transposing arrays is tiring and memory intensive, especially when dealing with stacks of stacks of arrays.

Moreover, sometimes we do actually need to transpose an array for some stupid operation and then want it back as it was. In such cases it would be very wasteful to _actually_ transpose huge data structures.

In [20]:
Na = 500
Nb = 200
Nc = 200
Nd = 30
C = np.random.randn(Na,Nb,Nc)
A = np.random.randn(Nd,Na)

t = time.time()
D = C.transpose([2,0,1])
print('\nStrided transposition.      Elapsed time is %1.2f seconds.' % ( time.time() - t ) )
t = time.time()
D = A @ D
print('\nStrided matmul-tiplication. Elapsed time is %1.2f seconds.' % ( time.time() - t ) )

t = time.time()
E = np.ascontiguousarray(C.transpose([2,0,1]))
print('\nActual transposition.       Elapsed time is %1.2f seconds.' % ( time.time() - t ) )
t = time.time()
E = A @ E
print('\nActual matmul-tiplication.  Elapsed time is %1.2f seconds.' % ( time.time() - t ) )

print('\nRelative difference between D and E is %.2e.' % ( np.linalg.norm(D-E)/np.linalg.norm(D) ) )


Strided transposition.      Elapsed time is 0.00 seconds.

Strided matmul-tiplication. Elapsed time is 9.18 seconds.

Actual transposition.       Elapsed time is 0.52 seconds.

Actual matmul-tiplication.  Elapsed time is 0.08 seconds.

Relative difference between D and E is 7.47e-16.


Now a little thought before passing to the next notebook: some of the Numpy features that we have seen and that we will discover in this course might seem... superfluous?

On the other hand, if you _know_ an operation _exist_ your brain will start _"think that way"_.
So don't be shy in learning new tools :)
